#!/usr/bin/env python3
"""
10_assign_0705_plant_numbers.py
=================================

Purpose
-------
For the 2025-07-05 Cojo/Perry batch (5 plants sharing one scan, one petal
per plant, laid out in a single left-to-right row with a numbered card
beneath), assign each segmented region to its specific plant and write
area_cm2 into petal_area_master.csv — replacing the
MULTI_PLANT_IMAGE_NOT_ASSIGNED placeholder written by
scripts/07_segment_petal_area.py.

The left-to-right plant order for each of the 6 images was read directly
off the card in each scan (not inferred from filename or region order —
see chat log, 2026-09-15), correcting for orientation where the scan was
saved upside-down. Two images run in DESCENDING plant-number order left
to right (Cojo_0003, Perry_0001, Perry_0002) — confirmed directly, not
assumed; getting this backwards would silently swap area values between
plants, so each entry below was read from the actual image, not
generated by a rule.

LEFT_TO_RIGHT_PLANT_ORDER value = the plant number of the region with the
SMALLEST centroid_col (leftmost, raw pixel frame) first.

Inputs (read-only): petal_area_segmentation_results.csv, petal_area_master.csv
Output: petal_area_master.csv updated in place (only the 30
2025-07-05 rows change); a copy of the pre-update file is NOT made here —
petal_area_master.csv is a derived file regenerated by this pipeline, not
a hand-edited source.
"""

from pathlib import Path
import pandas as pd

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent
OUT_DIR = PROJECT_ROOT / "data" / "processed" / "segmentation"
MASTER_PATH = PROJECT_ROOT / "data" / "processed" / "petal_area_master.csv"
RESULTS_PATH = OUT_DIR / "petal_area_segmentation_results.csv"

# Read directly off each card, left to right, correcting for orientation.
LEFT_TO_RIGHT_PLANT_ORDER = {
    "2025_07_05/Cojo_5_jul_25_0001.png":  [1, 2, 3, 4, 5],
    "2025_07_05/Cojo_5_jul_25_0002.png":  [6, 7, 8, 9, 10],
    "2025_07_05/Cojo_5_jul_25_0003.png":  [15, 14, 13, 12, 11],
    "2025_07_05/Perry_5_jul_25_0001.png": [5, 4, 3, 2, 1],
    "2025_07_05/Perry_5_jul_25_0002.png": [10, 9, 8, 7, 6],
    "2025_07_05/Perry_5_jul_25_0003.png": [11, 12, 13, 14, 15],
}


def main() -> None:
    results = pd.read_csv(RESULTS_PATH)
    master = pd.read_csv(MASTER_PATH)

    for col in ["area_flag", "measured_by", "notes"]:
        master[col] = master[col].astype(object)

    # Matched by parsed date, not a raw string/substring check — the "date"
    # column's on-disk format has drifted between M/D/YY and ISO before
    # (see scripts/11's docstring: an Excel save reverts it to M/D/YY), and
    # a substring check like "7/5" in the date string only matches one of
    # those formats.
    is_0705 = pd.to_datetime(master["date"], format="mixed", dayfirst=False) == pd.Timestamp("2025-07-05")

    review = []
    assigned_count = 0

    for image_path, plant_order in LEFT_TO_RIGHT_PLANT_ORDER.items():
        img_results = results[results["image_path"] == image_path]
        population = "Cojo" if "Cojo" in image_path else "Perry"

        ok = img_results[(img_results["method"] == "otsu_chroma") & (img_results["area_flag"] == "OK")]
        if len(ok) != 5:
            review.append({"image_path": image_path, "method": "otsu_chroma",
                            "reason": f"found {len(ok)} OK regions, expected 5"})
            continue
        ok_sorted = ok.sort_values("centroid_col")
        area_by_plant = dict(zip(plant_order, ok_sorted["area_cm2"]))

        for plant in plant_order:
            area_otsu = area_by_plant.get(plant)

            mask = (is_0705 &
                    (master["population"] == population) &
                    (master["plant"] == plant))
            if mask.sum() != 1:
                review.append({"image_path": image_path, "plant": plant,
                                "reason": f"expected 1 master row, found {mask.sum()}"})
                continue

            master.loc[mask, "area_cm2_otsu_chroma"] = area_otsu
            master.loc[mask, "area_cm2"] = area_otsu
            master.loc[mask, "n_petals_in_image"] = 5
            master.loc[mask, "area_flag"] = "OK"
            master.loc[mask, "measured_by"] = ("automated: otsu_chroma "
                                                "(scripts/07 + scripts/10_assign_0705_plant_numbers.py)")
            existing_notes = master.loc[mask, "notes"].fillna("").iloc[0]
            addendum = (f" [plant number read directly from the numbered card in {image_path} "
                        f"(5 plants share this scan); region matched by left-to-right position.]")
            if addendum not in existing_notes:  # avoid duplicating this note if the script is re-run
                master.loc[mask, "notes"] = existing_notes + addendum
            assigned_count += 1

    master.to_csv(MASTER_PATH, index=False)

    print(f"Assigned area_cm2 for {assigned_count} of 30 plant rows (2025-07-05).")
    if review:
        print(f"\n{len(review)} issues encountered:")
        print(pd.DataFrame(review).to_string(index=False))
    else:
        print("No issues — all 6 images had exactly 5 OK regions per method.")


if __name__ == "__main__":
    main()
