#!/usr/bin/env python3
"""
11_integrate_per_petal_data.py
================================

Two changes to petal_area_master.csv, both applied in place:

1. Parse the existing petal_flower column. A few dates (2025-05-20 Perry)
   already recorded individual petal weights as "petal 2", "petal 3",
   "petal 4" rows. Split that number out into a new petal_number column
   and normalize petal_flower back to plain "petal", so petal identity
   lives in one place instead of being embedded in a text label.
   Plain "petal" or "flower" rows get petal_number = NaN — NOT assumed
   to be petal 1; that would be guessing at an identity nothing confirms.

2. Integrate the per-petal segmentation measurements
   (data/processed/segmentation/petal_area_per_petal.csv — the 4-petals-
   per-image buckets, petal_number resolved via scripts/09) into master:
   - If a master row already exists for that exact (date, population,
     plant, petal_number) — e.g. 2025-05-20 Perry's pre-existing "petal 2"
     weight rows — fill in its area_cm2 fields; don't duplicate it.
   - Otherwise, ADD a new row for that petal: date/population/plant/
     petal_number plus the measured area, with plant-level facts (block,
     image_file_used, etc.) copied from that plant's existing row, and
     weight fields (wet_wgt_g, dry_wgt_g, ...) left blank — no weight was
     recorded for that specific petal.

Date-format note: petal_area_master.csv currently has dates as M/D/YY
(a side effect of an Excel save), while every derived file this pipeline
produces uses ISO (YYYY-MM-DD). Normalized to ISO on write-out here, to
stop the two formats silently drifting apart.

Inputs (read-only): petal_area_master.csv, petal_area_per_petal.csv
Output: petal_area_master.csv, rewritten in place (it is a derived file,
regenerated by this pipeline — not a hand-authored source).
"""

import re
from pathlib import Path

import pandas as pd

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent
MASTER_PATH = PROJECT_ROOT / "data" / "processed" / "petal_area_master.csv"
PER_PETAL_PATH = PROJECT_ROOT / "data" / "processed" / "segmentation" / "petal_area_per_petal.csv"

PLANT_LEVEL_COLS = ["block", "candidate_image_folder", "match_flag", "status",
                    "n_plants_expected", "n_images_found", "image_to_plant_ratio",
                    "image_file_used"]
WEIGHT_COLS = ["wet_wgt_g", "length_mm", "hand_area_cm2", "dry_wgt_g",
               "water_mg", "water_pct", "area_cm2_manual_check"]


def normalize_date(series: pd.Series) -> pd.Series:
    return pd.to_datetime(series, format="mixed", dayfirst=False).dt.strftime("%Y-%m-%d")


def main() -> None:
    master = pd.read_csv(MASTER_PATH)
    n_before = len(master)
    master["date"] = normalize_date(master["date"])

    for col in ["area_flag", "measured_by", "notes"]:
        master[col] = master[col].astype(object)

    # ---- Step 1: parse "petal N" out of petal_flower ----
    if "petal_number" not in master.columns:
        master.insert(master.columns.get_loc("petal_flower") + 1, "petal_number", pd.NA)

    pattern = re.compile(r"^petal\s+(\d+)$", re.IGNORECASE)
    n_parsed = 0
    for idx, val in master["petal_flower"].items():
        if isinstance(val, str):
            m = pattern.match(val.strip())
            if m:
                master.loc[idx, "petal_number"] = int(m.group(1))
                master.loc[idx, "petal_flower"] = "petal"
                n_parsed += 1
    print(f"Step 1: parsed petal number out of {n_parsed} existing 'petal N' rows.")

    # ---- Step 2: integrate per-petal segmentation data ----
    per_petal = pd.read_csv(PER_PETAL_PATH)
    n_merged, n_inserted = 0, 0
    new_rows = []

    for _, r in per_petal.iterrows():
        mask = ((master["date"] == r["date"]) & (master["population"] == r["population"]) &
                (master["plant"] == r["plant"]) & (master["petal_number"] == r["petal_number"]))
        if mask.sum() > 1:
            raise SystemExit(f"Ambiguous: {mask.sum()} existing rows match "
                              f"{r['date']} {r['population']} plant {r['plant']} petal {r['petal_number']}")
        if mask.sum() == 1:
            master.loc[mask, "area_cm2_otsu_chroma"] = r["area_cm2_otsu_chroma"]
            master.loc[mask, "area_cm2"] = r["area_cm2"]
            master.loc[mask, "measured_by"] = "automated: otsu_chroma (scripts/07 + scripts/09/11)"
            master.loc[mask, "area_flag"] = "OK"
            n_merged += 1
        else:
            plant_mask = ((master["date"] == r["date"]) & (master["population"] == r["population"]) &
                          (master["plant"] == r["plant"]))
            if plant_mask.sum() == 0:
                raise SystemExit(f"No existing plant row at all for {r['date']} {r['population']} "
                                  f"plant {r['plant']} — can't source plant-level fields.")
            template = master.loc[plant_mask].iloc[0].to_dict()
            new_row = {col: pd.NA for col in master.columns}
            new_row["date"] = r["date"]
            new_row["population"] = r["population"]
            new_row["plant"] = r["plant"]
            new_row["petal_flower"] = "petal"
            new_row["petal_number"] = r["petal_number"]
            for col in PLANT_LEVEL_COLS:
                new_row[col] = template.get(col)
            for col in WEIGHT_COLS:
                new_row[col] = pd.NA  # no weight recorded for this specific petal
            new_row["area_cm2_otsu_chroma"] = r["area_cm2_otsu_chroma"]
            new_row["area_cm2"] = r["area_cm2"]
            new_row["area_flag"] = "OK"
            new_row["measured_by"] = "automated: otsu_chroma (scripts/07 + scripts/09/11)"
            new_row["notes"] = (f"New row: petal {int(r['petal_number'])} of 4, measured from "
                                 f"{r['image_path']} (segmentation only; no separate weight recorded "
                                 f"for this specific petal).")
            new_rows.append(new_row)
            n_inserted += 1

    if new_rows:
        master = pd.concat([master, pd.DataFrame(new_rows)], ignore_index=True)

    master = master.sort_values(["date", "population", "plant", "petal_number"], na_position="first")
    master.to_csv(MASTER_PATH, index=False)

    print(f"Step 2: merged into {n_merged} existing rows, inserted {n_inserted} new rows.")
    print(f"\nRow count: {n_before} -> {len(master)}")
    print(f"petal_number now populated on {master['petal_number'].notna().sum()} rows.")


if __name__ == "__main__":
    main()
